- sticknotes-frontend/src/app/app.module.ts
- sticknotes-frontend/src/app/board/board.component.css
- sticknotes-frontend/src/app/board/board.component.html
- sticknotes-frontend/src/app/board/board.component.ts
- sticknotes-frontend/src/app/new-board/new-board.component.html
- sticknotes-frontend/src/app/new-board/new-board.component.ts
- sticknotes-frontend/src/app/new-note/new-note.component.css
- sticknotes-frontend/src/app/new-note/new-note.component.html
- sticknotes-frontend/src/app/new-note/new-note.component.spec.ts
- sticknotes-frontend/src/app/new-note/new-note.component.ts
- sticknotes-frontend/src/app/pipes.ts
- sticknotes-frontend/src/app/utility/util.ts
* Fix dragging note z-index bug
* Add on enter press event when creating a new board
* Add "+" buttons to the free slots of the board to allow creating new notes
* New note component layout
* Minor improvements and refactoring
> Fix board bugs, create new note component

- sticknotes-frontend/src/app/app.module.ts
- sticknotes-frontend/src/app/board/board.component.ts
- sticknotes-frontend/src/app/interfaces.ts
- sticknotes-frontend/src/app/new-note/new-note.component.css
- sticknotes-frontend/src/app/new-note/new-note.component.html
- sticknotes-frontend/src/app/new-note/new-note.component.ts
- sticknotes-frontend/src/app/services/api.service.ts
- sticknotes-frontend/src/app/services/notes-api.service.spec.ts
- sticknotes-frontend/src/app/services/notes-api.service.ts
* Working note create
* Add note service with mocked create for now
* Implement cross-component data sharing
> Create new note functionality

- sticknotes-frontend/src/app/app-routing.module.ts
- sticknotes-frontend/src/app/board-container/board-container.component.ts
- sticknotes-frontend/src/app/board/board.component.css
- sticknotes-frontend/src/app/board/board.component.html
- sticknotes-frontend/src/app/board/board.component.ts
- sticknotes-frontend/src/app/enums/state.enum.ts
- sticknotes-frontend/src/app/interfaces.ts
- sticknotes-frontend/src/app/new-board/new-board.component.ts
- sticknotes-frontend/src/app/new-note/new-note.component.html
- sticknotes-frontend/src/app/new-note/new-note.component.ts
- sticknotes-frontend/src/app/services/api.service.ts
- sticknotes-frontend/src/app/services/notes-api.service.ts
- sticknotes-frontend/src/app/utility/util.ts
* Implement notes editing
* Use mocked edit method in api service
* Reuse new-note component
> Edit note functionality

- sticknotes-frontend/package-lock.json
- sticknotes-frontend/package.json
- sticknotes-frontend/src/app/app.module.ts
- sticknotes-frontend/src/app/board-container/board-container.component.css
- sticknotes-frontend/src/app/board-container/board-container.component.html
- sticknotes-frontend/src/app/board-container/board-container.component.ts
- sticknotes-frontend/src/app/board/board.component.html
- sticknotes-frontend/src/app/board/board.component.ts
- sticknotes-frontend/src/app/interfaces.ts
- sticknotes-frontend/src/app/new-board/new-board.component.html
- sticknotes-frontend/src/app/new-board/new-board.component.ts
- sticknotes-frontend/src/app/services/api.service.ts
- sticknotes-frontend/src/app/services/board-api.service.ts
* Implement board edit
* Fixes and improvements
> Add edit board functionality, minor fixes

- sticknotes-frontend/src/app/board/board.component.ts
* Fix update abstract grid when deleting note
* Improve time complexity of adding note
> Fix delete

- sticknotes-frontend/src/app/board-container/board-container.component.html
- sticknotes-frontend/src/app/board-container/board-container.component.ts
- sticknotes-frontend/src/app/board/board.component.html
- sticknotes-frontend/src/app/board/board.component.ts
- sticknotes-frontend/src/app/boards-list/boards-list.component.ts
- sticknotes-frontend/src/app/new-board/new-board.component.ts
- sticknotes-frontend/src/app/new-note/new-note.component.html
- sticknotes-frontend/src/app/new-note/new-note.component.ts
- sticknotes-frontend/src/app/services/board-api.service.ts
- sticknotes-frontend/src/app/services/notes-api.service.ts
- sticknotes-frontend/src/app/utility/util.ts
- sticknotes-frontend/src/app/utility/vector.ts
* Add documentation of the frontend code
* A few minor refactorings
> Add more documentation on the frontend side

- sticknotes-frontend/src/app/board-container/board-container.component.html
- sticknotes-frontend/src/app/board-container/board-container.component.ts
Fixed mat-select form control, added snackbar for displaying errors
> Fix form control, add error snackbar

- sticknotes-frontend/src/app/board-container/board-container.component.html
- sticknotes-frontend/src/app/board-container/board-container.component.ts
- sticknotes-frontend/src/app/board-edit/board-edit.component.ts
- sticknotes-frontend/src/app/board/board.component.html
- sticknotes-frontend/src/app/board/board.component.ts
- sticknotes-frontend/src/app/interfaces.ts
- sticknotes-frontend/src/app/new-note/new-note.component.ts
- sticknotes-frontend/src/app/services/notes-api.service.ts
- sticknotes-frontend/src/app/services/user.service.ts
- sticknotes-frontend/src/app/user-list/user-list.component.html
- sticknotes-frontend/src/app/user-list/user-list.component.ts
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/models/User.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/BoardServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/UserListServletTest.java
* Rename field `key` to `id` in the User model
* Fix note update
* Use snackbar to display error messages from updating note
* Other fixes and improvements
> small fixes and improvements

- sticknotes-frontend/src/app/boards-list/boards-list.component.html
- sticknotes-frontend/src/app/boards-list/boards-list.component.ts
- sticknotes-frontend/src/app/interfaces.ts
- sticknotes-frontend/src/app/services/board-api.service.ts
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/models/User.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/serializers/WhiteboardPreviewSerializer.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/AppAbstractServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/LogoutUrlServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/MyBoardsListServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NoteAbstractServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserServlet.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/MyBoardsListServletTest.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
* Implementation of my boards endpoint
* Test setup updated with `logIn` method that provides a log in user mock in test
* Small fixes and improvements
> Implement my boards endpoint

- sticknotes-frontend/src/app/boards-list/boards-list.component.html
- sticknotes-frontend/src/app/boards-list/boards-list.component.ts
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/BoardServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserServlet.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/BoardServletTest.java
- fix BoardServletTest to work with Users API
- fix BoardServlet to work witth Users API
- temporary solution for restricting access to the /boards/ only for logged in users
> Boardlist front end integration

- sticknotesbackend/src/main/java/com/google/sticknotesbackend/AuthChecker.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/enums/Permission.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/models/UserBoardRole.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/AppAbstractServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/BoardAbstractServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/BoardNotesTranslatedServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/BoardServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/EditBoardServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/EditNoteServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NoteAbstractServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NoteServlet.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/BoardServletTest.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NoteServletTest.java
* Introduce permission object
* Introduce auth validators
> Access permissions

- sticknotes-frontend/src/app/app-routing.module.ts
- sticknotes-frontend/src/app/boards-list/boards-list.component.ts
- sticknotes-frontend/src/app/guards/auth.guard.spec.ts
- sticknotes-frontend/src/app/guards/auth.guard.ts
- sticknotes-frontend/src/app/new-board/new-board.component.css
* Implement guard service
* Remove style from dialog opening
> Add route guard and a small fix

- sticknotesbackend/src/main/java/com/google/sticknotesbackend/models/Note.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/models/UpdateQueryData.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/serializers/NoteSerializer.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NotesUpdateServlet.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesUpdateServletTest.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
-add endpoint for notes update
-not tested yet (please do not review NotesUpdateServletTest.java)
> Cache backend

- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/BoardServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/EditBoardServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/EditNoteServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NoteServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
* Removes deprecated code, closes #72
> Remove deprecated code

- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NoteServlet.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NoteServletTest.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
* Fixes the bug when > 1 users create a note in the same cell, closes #71
> Fix crreate note on the same spot

- sticknotes-frontend/src/app/board/board.component.ts
- sticknotes-frontend/src/app/interfaces.ts
- sticknotes-frontend/src/app/services/board-api.service.ts
- sticknotes-frontend/src/app/services/notes-api.service.ts
> Updates improved frontend

- sticknotesbackend/src/main/java/com/google/sticknotesbackend/models/Whiteboard.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/serializers/WhiteboardSerializer.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/serializers/WhiteboardWithoutNotesSerializer.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/BoardServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/BoardUpdatesServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/EditBoardServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/EditNoteServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NoteServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NotesUpdateServlet.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/BoardUpdatesServletTest.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesUpdateServletTest.java
* Implementation of board updates endpoint
> Board updates

- sticknotes-frontend/src/app/board/board.component.html
- sticknotes-frontend/src/app/board/board.component.ts
* Disable edit, delete and move buttons for not authors
> Fix note edit permission

- sticknotes-frontend/src/app/board-container/board-container.component.ts
- sticknotes-frontend/src/app/board/board.component.ts
> Add reset translate option

- sticknotes-frontend/src/app/boards-list/boards-list.component.css
- sticknotes-frontend/src/app/boards-list/boards-list.component.html
- sticknotes-frontend/src/app/boards-list/boards-list.component.ts
- sticknotes-frontend/src/app/interfaces.ts
- sticknotes-frontend/src/app/services/board-api.service.ts
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/serializers/WhiteboardPreviewSerializer.java
> Implement frontend part of board deleting

- sticknotes-frontend/src/app/board/board.component.ts
* Closes #93
* Grid was not updated properly when note was deleted, fixed here
> Run translation again if note content was edited

- sticknotes-frontend/src/app/boards-list/boards-list.component.css
- sticknotes-frontend/src/app/boards-list/boards-list.component.html
- sticknotes-frontend/src/app/boards-list/boards-list.component.ts
- sticknotes-frontend/src/app/services/user.service.ts
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/LogoutUrlServlet.java
> Add logout button

- README.md
@AndrzejPodo I thought our readme doesn't have a very important piece of information about our project - an answer to question "what is our project?". So here is the first attempt to answer this question, feel free to improve!
> Attempt to fix readme

- sticknotes-frontend/src/app/app.module.ts
- sticknotes-frontend/src/app/board/board.component.css
- sticknotes-frontend/src/app/board/board.component.html
- sticknotes-frontend/src/app/board/board.component.ts
- sticknotes-frontend/src/app/enums/board-grid-line-type.enum.ts
- sticknotes-frontend/src/app/interfaces.ts
- sticknotes-frontend/src/app/new-board/new-board.component.html
- sticknotes-frontend/src/app/new-grid-line/new-grid-line.component.css
- sticknotes-frontend/src/app/new-grid-line/new-grid-line.component.html
- sticknotes-frontend/src/app/new-grid-line/new-grid-line.component.spec.ts
- sticknotes-frontend/src/app/new-grid-line/new-grid-line.component.ts
- sticknotes-frontend/src/app/services/board-api.service.ts
- sticknotes-frontend/src/app/services/shared-board.service.ts
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/NotesboardContextListener.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/enums/BoardGridLineType.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/models/BoardGridLine.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/models/Whiteboard.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/serializers/WhiteboardSerializer.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/serializers/WhiteboardWithoutNotesSerializer.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/BoardGridLineServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/BoardServlet.java
- sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NoteServlet.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/BoardGridLineServletTest.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NoteServletTest.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
- sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/UserListServletTest.java
This is the very start of the feature request #108, I decided to make a PR now to let you review it until it will grow very large
> Rows and columns names
